apiVersion: v1
kind: Namespace
metadata:
  name: test-liqo
  labels:
    # Questa è la label di whitelisting per il tuo controller
    liqo-helper.io/monitor: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test-liqo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: my-container
        image: nginx
      # Forziamo il Pod sul nodo virtuale di Liqo
      nodeSelector:
        liqo.io/type: virtual-node
      # Tolleriamo il taint di default del virtual node di Liqo
      tolerations:
      - key: "virtual-node.liqo.io/not-allowed"
        operator: "Exists"
        effect: "NoExecute"