apiVersion: v2
name: liqo-dynamic-offloader
description: Event-driven Kubernetes operator for automatic recovery of Liqo offloading.
type: application
version: 0.1.1
appVersion: "0.1.0"
keywords:
  - kubernetes
  - liqo
  - operator